# vote_coefficients_0xAA40E2E5c8df03d792A52B5458959C320F86ca18_1

In [14]:
import os
from pathlib import Path
import numpy as np
import requests
import pandas as pd

from sbdata.FlipsideApi import FlipsideApi



# Set path to data folder
current_dir = Path(os.getcwd())
FOLDER_NAME = 'community_round'
CHAIN = 'optimism'
PATH_TO_EXPORT = os.path.join(current_dir.parent.parent, 'tx_data', FOLDER_NAME)
DATA_DIR = os.path.join(current_dir.parent.parent, 'data-regen-rangers')
DATA_DIR_GITCOIN = os.path.join(current_dir.parent.parent, 'data-gitcoin')
GRANT_ROUND_ID = '0x984e29dCB4286c2D9cbAA2c238AfDd8A191Eefbc'
CHAIN_ID = '10'


# read the address from oss grant

api_key = os.environ['FLIPSIDE_API_KEY']
flipside_api = FlipsideApi(api_key, max_address=400)
PATH_TO_VOTES = os.path.join(DATA_DIR_GITCOIN, 'citizen-votes.csv')
# PATH_TO_GRANTS = os.path.join(DATA_DIR, "all-allo-rounds.csv")
# PATH_TO_PROJECTS = os.path.join(DATA_DIR, "projects_QmQurt.csv")
# PATH_TO_VOTES_GITCOIN = os.path.join(DATA_DIR_GITCOIN, CSV_GITCOIN_GRANTS)

In [136]:
# def load_round_votes_data(chain_id, round_id):
#     votes_url = 'https://indexer-grants-stack.gitcoin.co/data/' + chain_id + '/rounds/' + round_id + '/votes.json'
#     try:
#         # download the Votes JSON data from the URL
#         response = requests.get(votes_url)
#         if response.status_code == 200:
#             votes_data = response.json()
#         df = pd.DataFrame(votes_data)
#         return df
#     except:
#         return pd.DataFrame()

In [137]:
# # load data
# df_votes = df_votes = load_round_votes_data(CHAIN_ID, GRANT_ROUND_ID)

In [138]:
df_votes = pd.read_csv(PATH_TO_VOTES)
# df_grants = pd.read_csv(PATH_TO_GRANTS)
# df_application = pd.read_csv(PATH_TO_PROJECTS)
# Lowercase all addresses because flipside api return lowercase address
#id,projectId,applicationId,roundId,token,voter,grantAddress,amount,amountUSD,coefficient,status,last_score_timestamp,type,success,rawScore,threshold
# df_grants['Round ID'] = df_grants['Round ID'].str.lower()
# str_columns_votes = ['id', 'transaction', 'projectId', 'roundId', 'voter', 'grantAddress']
# df_votes[str_columns_votes] = df_votes[str_columns_votes].applymap(lambda x: x.lower())

# str_columns_application = ['id', 'roundId', 'metadata.application.round', 'metadata.application.recipient']
# df_application[str_columns_application] = df_application[str_columns_application].applymap(lambda x: str(x).lower())

# round_id = df_grants[df_grants['Round name'] == 'Web3 Community and Education']['Round ID'].values[0]
array_unique_address = df_votes['voter'].unique()

array_unique_address = np.char.lower(array_unique_address.astype(str))

In [10]:
import os
from sbdata.FlipsideApi import FlipsideApi

In [12]:
api_key = os.environ['FLIPSIDE_API_KEY2']
flipside_api = FlipsideApi(api_key, page_size=80000)
sql = "SELECT ADDRESS, ADDRESS_NAME, LABEL_SUBTYPE, PROJECT_NAME FROM crosschain.core.address_labels WHERE BLOCKCHAIN ='optimism'"
df = flipside_api.execute_query(sql=sql)

In [25]:
df.to_csv(os.path.join(DATA_DIR, 'optimism_address_labels.csv'), index=False)

In [24]:
df['address_name'] = df['address_name'].astype(str)
df.to_parquet(os.path.join(DATA_DIR, 'optimism_address_labels.parquet'), index=False)

In [ ]:
# load from hugging face
from datasets import load_dataset, Dataset
ds = load_dataset('Poupou/test-download')
df = ds['train'].to_pandas()
df.head()

Found cached dataset parquet (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___parquet/Poupou--test-download-f38f67bb8061fbd1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

,tx_hash,block_timestamp,from_address,to_address,gas_limit,gas_used,tx_fee,eth_value,__row_index,EOA
0,0x17a3074efc6e1b4bb0cbe4fd111c0108ab1848575d0a...,2022-09-22T23:10:30.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,200000,21000,0.000039,0.00130,264,0x000000006f457c0f8f560333d9c2877287d92a92
1,0x1e66f9eea3f9a5cfc2c7a68a0c1f7a1689ea5d0b8256...,2023-04-01T04:10:28.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0xcd98de456b233d828e4419eb1c24424fa02d8714,165645,158544,0.000161,0.00269,1770,0x000000006f457c0f8f560333d9c2877287d92a92
2,0x70e8306dc8cb0c4f963dd71bc370ad5429b0347027f8...,2023-04-01T04:06:56.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,21000,21000,0.000083,0.00300,1771,0x000000006f457c0f8f560333d9c2877287d92a92
3,0x622962d520b7befd2b53c4fe363aa4c56f501bc3efeb...,2023-04-04T22:17:09.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x864edff094a4974ce2f665aad92e8d05ed5989cb,155980,149030,0.000297,0.00069,2160,0x000000006f457c0f8f560333d9c2877287d92a92
4,0xbaf374a6a3b28859407a7449de70568c63544355eee7...,2023-05-16T13:39:35.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x787ba605b1764c5bd2d71f0e72ca0f4ef03ef0da,123976,117533,0.000241,0.00000,3800,0x000000006f457c0f8f560333d9c2877287d92a92

In [ ]:
# load from hugging face
from datasets import load_dataset, Dataset
ds = load_dataset('Poupou/test-download')
df = ds['train'].to_pandas()
df.head()

Found cached dataset parquet (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___parquet/Poupou--test-download-f38f67bb8061fbd1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

,tx_hash,block_timestamp,from_address,to_address,gas_limit,gas_used,tx_fee,eth_value,__row_index,EOA
0,0x17a3074efc6e1b4bb0cbe4fd111c0108ab1848575d0a...,2022-09-22T23:10:30.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,200000,21000,0.000039,0.00130,264,0x000000006f457c0f8f560333d9c2877287d92a92
1,0x1e66f9eea3f9a5cfc2c7a68a0c1f7a1689ea5d0b8256...,2023-04-01T04:10:28.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0xcd98de456b233d828e4419eb1c24424fa02d8714,165645,158544,0.000161,0.00269,1770,0x000000006f457c0f8f560333d9c2877287d92a92
2,0x70e8306dc8cb0c4f963dd71bc370ad5429b0347027f8...,2023-04-01T04:06:56.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,21000,21000,0.000083,0.00300,1771,0x000000006f457c0f8f560333d9c2877287d92a92
3,0x622962d520b7befd2b53c4fe363aa4c56f501bc3efeb...,2023-04-04T22:17:09.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x864edff094a4974ce2f665aad92e8d05ed5989cb,155980,149030,0.000297,0.00069,2160,0x000000006f457c0f8f560333d9c2877287d92a92
4,0xbaf374a6a3b28859407a7449de70568c63544355eee7...,2023-05-16T13:39:35.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x787ba605b1764c5bd2d71f0e72ca0f4ef03ef0da,123976,117533,0.000241,0.00000,3800,0x000000006f457c0f8f560333d9c2877287d92a92

In [ ]:
# load from hugging face
from datasets import load_dataset, Dataset
ds = load_dataset('Poupou/test-download')
df = ds['train'].to_pandas()
df.head()

Found cached dataset parquet (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___parquet/Poupou--test-download-f38f67bb8061fbd1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

,tx_hash,block_timestamp,from_address,to_address,gas_limit,gas_used,tx_fee,eth_value,__row_index,EOA
0,0x17a3074efc6e1b4bb0cbe4fd111c0108ab1848575d0a...,2022-09-22T23:10:30.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,200000,21000,0.000039,0.00130,264,0x000000006f457c0f8f560333d9c2877287d92a92
1,0x1e66f9eea3f9a5cfc2c7a68a0c1f7a1689ea5d0b8256...,2023-04-01T04:10:28.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0xcd98de456b233d828e4419eb1c24424fa02d8714,165645,158544,0.000161,0.00269,1770,0x000000006f457c0f8f560333d9c2877287d92a92
2,0x70e8306dc8cb0c4f963dd71bc370ad5429b0347027f8...,2023-04-01T04:06:56.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,21000,21000,0.000083,0.00300,1771,0x000000006f457c0f8f560333d9c2877287d92a92
3,0x622962d520b7befd2b53c4fe363aa4c56f501bc3efeb...,2023-04-04T22:17:09.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x864edff094a4974ce2f665aad92e8d05ed5989cb,155980,149030,0.000297,0.00069,2160,0x000000006f457c0f8f560333d9c2877287d92a92
4,0xbaf374a6a3b28859407a7449de70568c63544355eee7...,2023-05-16T13:39:35.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x787ba605b1764c5bd2d71f0e72ca0f4ef03ef0da,123976,117533,0.000241,0.00000,3800,0x000000006f457c0f8f560333d9c2877287d92a92

In [ ]:
# load from hugging face
from datasets import load_dataset, Dataset
ds = load_dataset('Poupou/test-download')
df = ds['train'].to_pandas()
df.head()

Found cached dataset parquet (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___parquet/Poupou--test-download-f38f67bb8061fbd1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

,tx_hash,block_timestamp,from_address,to_address,gas_limit,gas_used,tx_fee,eth_value,__row_index,EOA
0,0x17a3074efc6e1b4bb0cbe4fd111c0108ab1848575d0a...,2022-09-22T23:10:30.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,200000,21000,0.000039,0.00130,264,0x000000006f457c0f8f560333d9c2877287d92a92
1,0x1e66f9eea3f9a5cfc2c7a68a0c1f7a1689ea5d0b8256...,2023-04-01T04:10:28.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0xcd98de456b233d828e4419eb1c24424fa02d8714,165645,158544,0.000161,0.00269,1770,0x000000006f457c0f8f560333d9c2877287d92a92
2,0x70e8306dc8cb0c4f963dd71bc370ad5429b0347027f8...,2023-04-01T04:06:56.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,21000,21000,0.000083,0.00300,1771,0x000000006f457c0f8f560333d9c2877287d92a92
3,0x622962d520b7befd2b53c4fe363aa4c56f501bc3efeb...,2023-04-04T22:17:09.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x864edff094a4974ce2f665aad92e8d05ed5989cb,155980,149030,0.000297,0.00069,2160,0x000000006f457c0f8f560333d9c2877287d92a92
4,0xbaf374a6a3b28859407a7449de70568c63544355eee7...,2023-05-16T13:39:35.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x787ba605b1764c5bd2d71f0e72ca0f4ef03ef0da,123976,117533,0.000241,0.00000,3800,0x000000006f457c0f8f560333d9c2877287d92a92

In [ ]:
# load from hugging face
from datasets import load_dataset, Dataset
dsv = load_dataset('Poupou/test-download')
dfv = dsv['train'].to_pandas()
dfv.head()

In [6]:
# load from hugging face
from datasets import load_dataset, Dataset
ds = load_dataset('Poupou/test-download')
df = ds['train'].to_pandas()
df.head()

Found cached dataset parquet (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___parquet/Poupou--test-download-f38f67bb8061fbd1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

,tx_hash,block_timestamp,from_address,to_address,gas_limit,gas_used,tx_fee,eth_value,__row_index,EOA
0,0x17a3074efc6e1b4bb0cbe4fd111c0108ab1848575d0a...,2022-09-22T23:10:30.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,200000,21000,0.000039,0.00130,264,0x000000006f457c0f8f560333d9c2877287d92a92
1,0x1e66f9eea3f9a5cfc2c7a68a0c1f7a1689ea5d0b8256...,2023-04-01T04:10:28.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0xcd98de456b233d828e4419eb1c24424fa02d8714,165645,158544,0.000161,0.00269,1770,0x000000006f457c0f8f560333d9c2877287d92a92
2,0x70e8306dc8cb0c4f963dd71bc370ad5429b0347027f8...,2023-04-01T04:06:56.000Z,0xacd03d601e5bb1b275bb94076ff46ed9d753435a,0x000000006f457c0f8f560333d9c2877287d92a92,21000,21000,0.000083,0.00300,1771,0x000000006f457c0f8f560333d9c2877287d92a92
3,0x622962d520b7befd2b53c4fe363aa4c56f501bc3efeb...,2023-04-04T22:17:09.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x864edff094a4974ce2f665aad92e8d05ed5989cb,155980,149030,0.000297,0.00069,2160,0x000000006f457c0f8f560333d9c2877287d92a92
4,0xbaf374a6a3b28859407a7449de70568c63544355eee7...,2023-05-16T13:39:35.000Z,0x000000006f457c0f8f560333d9c2877287d92a92,0x787ba605b1764c5bd2d71f0e72ca0f4ef03ef0da,123976,117533,0.000241,0.00000,3800,0x000000006f457c0f8f560333d9c2877287d92a92

In [7]:
ds

DatasetDict({
    train: Dataset({
        features: ['tx_hash', 'block_timestamp', 'from_address', 'to_address', 'gas_limit', 'gas_used', 'tx_fee', 'eth_value', '__row_index', 'EOA'],
        num_rows: 2822339
    })
})

In [4]:
from datasets import load_dataset

# Load the dataset from the model hub
dataset_features = load_dataset('Poupou/test-voter_features')

Found cached dataset csv (C:/Users/DELL Admin/.cache/huggingface/datasets/Poupou___csv/Poupou--test-voter_features-8d45854b6d96c4ca/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
100%|██████████| 1/1 [00:00<00:00, 142.85it/s]

In [3]:
dataset_features['train'].to_pandas()

,address,seed_same_naive,seed_same,seed_suspicious,less_5_tx,less_10_tx,interacted_other_ctbt,lcs,cluster_size_lcs,mean_score_lcs,...,has_interaction_toxic,has_no_pool_interaction,count_interaction_with_airdrop_m,is_airdrop_master,count_interaction_with_tornado,count_interaction_with_disperse,has_interaction_airdrop_m,has_interaction_tornado,has_interaction_disperse,flagged
0,0x000000006f457c0f8f560333d9c2877287d92a92,True,True,False,False,False,True,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
1,0x000128fa45d79dc9af8016da242781f12c363fd5,True,True,False,False,False,False,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
2,0x000569d03483abb8949f729908465e65c4bdb243,False,True,True,False,True,False,"{""address"":{""0"":""0x01b527a67d82692c0d4ece55a1b...",48.0,0.2,...,False,True,0,False,0,0,False,False,False,True
3,0x0015f1d02b55ec9edd7536ca628fd30361252ebf,True,True,False,False,False,True,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
4,0x0015f91e93996d7e5979bf32391a8be59aadd606,True,True,False,False,False,True,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17018,0xfff0016550753ce0b4b70704ae88aaf154bec4bf,False,False,False,False,False,False,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
17019,0xfff00f4eb5c003db1f59f86428efd6b7cc2ae5f7,False,False,False,False,False,True,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False
17020,0xfffa92ec41925b4f4fa44cef294083cbe16b02f5,True,True,False,False,False,False,None,0.0,0.0,...,False,False,0,False,0,0,False,False,False,False
17021,0xfffb43b6b6048adc32ded4fcedc429b17e7ea72d,False,False,False,False,False,False,None,0.0,0.0,...,False,False,0,False,0,0,False,False,False,False
17022,0xffff7c33c874929d1daf8a208844e4a1d17d37a6,True,True,False,False,False,False,None,0.0,0.0,...,False,True,0,False,0,0,False,False,False,False

In [9]:
df_tx = ds['train'].to_pandas()

# Test Flipside to infer exchange dex or regular user

In [26]:
sql_template = """
WITH
  transactions AS (
    SELECT
      BLOCK_TIMESTAMP,
      TX_FEE,
      FROM_ADDRESS AS EOA
    FROM
      optimism.core.fact_transactions
    WHERE
      FROM_ADDRESS IN (%s)
    UNION ALL
    SELECT
      BLOCK_TIMESTAMP,
      TX_FEE,
      TO_ADDRESS AS EOA
    FROM
      optimism.core.fact_transactions
    WHERE
      TO_ADDRESS IN (%s)
  )
SELECT
  EOA,
  COUNT(*) as n_tx,
  TIMESTAMPDIFF(MINUTE, MIN(BLOCK_TIMESTAMP), CURRENT_TIMESTAMP()) as age,
  COUNT(*) / TIMESTAMPDIFF(MINUTE, MIN(BLOCK_TIMESTAMP), CURRENT_TIMESTAMP()) as tx_min,
  AVG(TX_FEE) as avg_tx_fee,
  STDDEV(TX_FEE) as std_tx_fee
FROM
  transactions
GROUP BY
  EOA;
"""

In [31]:
array_address = df['address'].unique()[:10]

In [32]:
array_address.shape

(10,)

In [33]:
api_key = os.environ['FLIPSIDE_API_KEY2']
flipside_api = FlipsideApi(api_key, page_size=50000, max_address=5)

list_df = []

q, r = divmod(len(array_address), flipside_api.MAX_ADDRESS)
if r != 0:
    q += 1
for i in range(q):
    start_index = i * flipside_api.MAX_ADDRESS
    end_index = (i + 1) * flipside_api.MAX_ADDRESS
    print(
        f"Extracting transactions for address: {start_index} - {end_index}")
    array_address_slice = array_address[start_index:end_index]
    str_address_slice = flipside_api.get_string_address(array_address_slice)
    sql = sql_template % (str_address_slice, str_address_slice)
    df = flipside_api.execute_query(sql=sql)
    list_df.append(df)
details_address = pd.concat(list_df)
print(details_address.shape)
details_address.head()

Extracting transactions for address: 0 - 5
Extracting transactions for address: 5 - 10

,eoa,n_tx,age,tx_min,avg_tx_fee,std_tx_fee,__row_index
0,0x0105d09f5ea12dd2fa6232ff76044c895f06a920,4,232854,0.000017,0.000104,0.000031,0

get_string_address(array_address)